[package]
name = "prost-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11"
rumqttc = "0.22"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
chrono-tz = "0.8"


[build-dependencies]
prost-build = "0.11"